name: Regenerate from WSDL

on:
  schedule:
    - cron:  '0 8 * * *'
# on: [push]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Regenerate files
      run: |
        rake -f Rakefile flightxml:generate
    - name: Create Pull Request
      run: |
        if [ ! -z "$(git status --porcelain)" ]; then
          branch_name="`date "+%Y-%m-%d"`-wsdl-update"
          git checkout -b $branch_name
          git add .
          git config user.email jake@tolerable.tech
          git config user.name Jake Wilkins
          git commit -m "Regenerate based on updated WSDL"
          git push origin $branch_name

          echo -n '{"title": "Regenerate for updated WSDL", "head": "' > body.json
          echo -n $branch_name >> body.json
          echo '", "base": "master", "body": "FlightAware published an updated WSDL. This regenerates our code based upon updated definitions"}' >> body.json

          cat body.json

          curl --request POST\
            --url https://api.github.com/repos/jakewilkins/flightxml-json/pulls\
            --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            --header 'content-type: application/json' \
            --data @body.json
        else
          echo "No changes detected, not creating a pull request."
        fi
